/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-high": "#2a2a2a",
        "surface-container-low": "#1b1b1b",
        "outline": "#919191",
        "on-surface-variant": "#c6c6c6",
        "on-primary-fixed": "#ffffff",
        "primary-fixed-dim": "#454747",
        "on-surface": "#e2e2e2",
        "on-secondary": "#1b1c1c",
        "surface-tint": "#c6c6c7",
        "error": "#ffb4ab",
        "background": "#131313",
        "inverse-on-surface": "#303030",
        "on-background": "#e2e2e2",
        "surface-dim": "#131313",
        "primary": "#ffffff",
        "tertiary-container": "#919090",
        "on-secondary-container": "#e5e2e1",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#adabaa",
        "outline-variant": "#474747",
        "on-primary": "#1a1c1c",
        "on-tertiary-fixed-variant": "#e4e2e1",
        "tertiary-fixed-dim": "#474747",
        "secondary-fixed": "#c8c6c5",
        "on-secondary-fixed-variant": "#3c3b3b",
        "on-tertiary": "#1b1c1c",
        "surface-container-lowest": "#0e0e0e",
        "tertiary-fixed": "#5f5e5e",
        "surface-container": "#1f1f1f",
        "surface-bright": "#393939",
        "inverse-surface": "#e2e2e2",
        "on-primary-container": "#000000",
        "surface": "#131313",
        "on-error": "#690005",
        "surface-variant": "#353535",
        "on-tertiary-container": "#000000",
        "on-secondary-fixed": "#1b1c1c",
        "inverse-primary": "#5d5f5f",
        "surface-container-highest": "#353535",
        "primary-fixed": "#5d5f5f",
        "tertiary": "#e4e2e1",
        "on-primary-fixed-variant": "#e2e2e2",
        "primary-container": "#d4d4d4",
        "on-tertiary-fixed": "#ffffff",
        "secondary-container": "#474746",
        "secondary": "#c8c6c5",
        "neon-green": "#22c55e",
        "secondary-green": "#16a34a"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.3rem", "lg": "0.6rem", "xl": "1rem", "full": "9999px"}
    },
  },
  plugins: [],
}
